spring.datasource.url=jdbc:sqlserver://localhost:1433;database=Java421;trustServerCertificate=true;
spring.datasource.username=AppUser
spring.datasource.password=AppUser
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#???????? ?????? ? ??
#spring.jpa.hibernate.ddl-auto=create

#???????? ?????? ? ???????? ?? ????? ?????????? ?????????? (???. ??? ????????????)
spring.jpa.hibernate.ddl-auto=create-drop

#?????????? ??????, ?????????? ??????????? ??????/??????
#spring.jpa.hibernate.ddl-auto=update