insert into pricelist (name,type) VALUES ('base',1);
insert into pricelist (name,type) VALUES ('capers',1);
insert into pricelist (name,type) VALUES ('cheese add',1);
insert into pricelist (name,type) VALUES ('halapeno',1);
insert into pricelist (name,type) VALUES ('mushroom',1);
insert into pricelist (name,type) VALUES ('base',2);
insert into pricelist (name,type) VALUES ('tomatoes',2);
insert into pricelist (name,type) VALUES ('mozarella',2);
insert into pricelist (name,type) VALUES ('parmesan',2);
insert into pricelist (name,type) VALUES ('gorgonzola',2);
insert into pricelist (name,type) VALUES ('ham',2);
insert into pricelist (name,type) VALUES ('ananas',2);
insert into pricelist (name,type) VALUES ('basil',2);
insert into pricelist (name,type) VALUES ('chiken',2);
insert into pricelist (name,type) VALUES ('sweet pepper',2);
insert into pricelist (name,type) VALUES ('garlic',2);
insert into pricelist (name,type) VALUES ('red sauce',2);
insert into pricelist (name,type) VALUES ('white sauce',2);
insert into pricelist (name,type) VALUES ('Caprichosa',3);
insert into pricelist (name,type) VALUES ('Quattro formaggi',3);
insert into pricelist (name,type) VALUES ('Hawaii',3);
insert into pricelist (name,type) VALUES ('Margarita',2);

update pricelist SET price=600.00 WHERE id=2;
update pricelist SET price=300.00 WHERE id=3;
update pricelist SET price=350.00 WHERE id=4;
update pricelist SET price=500.00 WHERE id=5;
update pricelist SET price=80.00 WHERE id=6;
update pricelist SET price=85.00 WHERE id=7;
update pricelist SET price=40.00 WHERE id=8;
update pricelist SET price=30.00 WHERE id=9;
update pricelist SET price=40.00 WHERE id=10;
update pricelist SET price=100.00 WHERE id=11;
update pricelist SET price=20.00 WHERE id=12;
update pricelist SET price=30.00 WHERE id=13;
update pricelist SET price=30.00 WHERE id=14;
update pricelist SET price=35.00 WHERE id=15;
update pricelist SET price=60.00 WHERE id=16;
update pricelist SET price=20.00 WHERE id=17;
update pricelist SET price=10.00 WHERE id=18;
update pricelist SET price=55.00 WHERE id=19;
update pricelist SET price=20.00 WHERE id=20;
update pricelist SET price=10.00 WHERE id=21;
update pricelist SET price=5.00 WHERE id=22;
update pricelist SET price=6.00 WHERE id=23;
