spring.datasource.url=jdbc:sqlserver://localhost:1433;databasename=Java421;trustServerCertificate=true;
spring.datasource.username=AppUser
spring.datasource.password=AppUser
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#создание таблиц в БД
#spring.jpa.hibernate.ddl-auto=create

#создание таблиц и удаление их после завершения приложения (исп. при тестировании)
#spring.jpa.hibernate.ddl-auto=create-drop

#обновление данных, добавление недостающих данных/таблиц
#spring.jpa.hibernate.ddl-auto=update

#????????? ?? ?????. ????????? ??????? ????????? ??
#spring.jpa.hibernate.ddl-auto=validate

#??? ????????????? ???? ? ??
#spring.jpa.hibernate.ddl-auto=none


#
#spring.datasource.url=jdbc:sqlserver://localhost:1433;database=Java421;
#  spring.datasource.username=AppUser\
#  spring.datasource.password=AppUser\
#  spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver\
#  #localhost#127.0.0.1#192.168.0.103

